sites = [
    {
        "site_id": "SITE-001",
        "site_name": "Fort Liberty Sustainment Hub",
        "region": "Southeast",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-002",
        "site_name": "Fort Cavazos Readiness Center",
        "region": "Southwest",
        "site_type": "Readiness Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-003",
        "site_name": "Camp Pendleton Logistics Node",
        "region": "West",
        "site_type": "Logistics Node",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-004",
        "site_name": "Joint Base Lewis-McChord Supply Hub",
        "region": "Pacific Northwest",
        "site_type": "Supply Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-005",
        "site_name": "Fort Stewart Maintenance Depot",
        "region": "Southeast",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-006",
        "site_name": "Fort Drum Sustainment Center",
        "region": "Northeast",
        "site_type": "Sustainment Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-007",
        "site_name": "Fort Carson Regional Supply Hub",
        "region": "Mountain West",
        "site_type": "Supply Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-008",
        "site_name": "Fort Riley Equipment Readiness Site",
        "region": "Midwest",
        "site_type": "Readiness Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-009",
        "site_name": "Fort Bliss Mobility Support Depot",
        "region": "Southwest",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-010",
        "site_name": "Fort Campbell Logistics Support Center",
        "region": "Southeast",
        "site_type": "Logistics Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-011",
        "site_name": "Fort Moore Sustainment Yard",
        "region": "Southeast",
        "site_type": "Sustainment Yard",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-012",
        "site_name": "Fort Leonard Wood Supply Center",
        "region": "Midwest",
        "site_type": "Supply Center",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-013",
        "site_name": "Fort Sill Field Maintenance Site",
        "region": "Southwest",
        "site_type": "Maintenance Site",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-014",
        "site_name": "Fort Huachuca Communications Parts Hub",
        "region": "Southwest",
        "site_type": "Supply Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-015",
        "site_name": "Fort Irwin Training Logistics Node",
        "region": "West",
        "site_type": "Logistics Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-016",
        "site_name": "Fort Novosel Aviation Sustainment Center",
        "region": "Southeast",
        "site_type": "Aviation Sustainment Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-017",
        "site_name": "Fort Johnson Readiness Support Site",
        "region": "South Central",
        "site_type": "Readiness Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-018",
        "site_name": "Fort Wainwright Arctic Logistics Hub",
        "region": "Alaska",
        "site_type": "Logistics Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-019",
        "site_name": "Joint Base Elmendorf-Richardson Supply Depot",
        "region": "Alaska",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-020",
        "site_name": "Schofield Barracks Pacific Readiness Hub",
        "region": "Pacific",
        "site_type": "Readiness Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-021",
        "site_name": "Pearl Harbor Fleet Supply Center",
        "region": "Pacific",
        "site_type": "Supply Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-022",
        "site_name": "San Diego Naval Logistics Facility",
        "region": "West",
        "site_type": "Logistics Facility",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-023",
        "site_name": "Norfolk Fleet Sustainment Depot",
        "region": "Mid-Atlantic",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-024",
        "site_name": "Mayport Maritime Supply Node",
        "region": "Southeast",
        "site_type": "Supply Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-025",
        "site_name": "Jacksonville Aviation Parts Center",
        "region": "Southeast",
        "site_type": "Aviation Parts Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-026",
        "site_name": "Pensacola Training Supply Hub",
        "region": "Southeast",
        "site_type": "Supply Hub",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-027",
        "site_name": "Eglin Range Support Depot",
        "region": "Southeast",
        "site_type": "Depot",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-028",
        "site_name": "Tyndall Equipment Recovery Site",
        "region": "Southeast",
        "site_type": "Recovery Site",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-029",
        "site_name": "MacDill Joint Logistics Center",
        "region": "Southeast",
        "site_type": "Logistics Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-030",
        "site_name": "Patrick Space Systems Supply Hub",
        "region": "Southeast",
        "site_type": "Supply Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-031",
        "site_name": "Robins Air Logistics Complex",
        "region": "Southeast",
        "site_type": "Air Logistics Complex",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-032",
        "site_name": "Warner Robins Component Repair Depot",
        "region": "Southeast",
        "site_type": "Repair Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-033",
        "site_name": "Charleston Strategic Lift Support Site",
        "region": "Southeast",
        "site_type": "Support Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-034",
        "site_name": "Shaw Regional Readiness Center",
        "region": "Southeast",
        "site_type": "Readiness Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-035",
        "site_name": "Seymour Johnson Maintenance Support Hub",
        "region": "Southeast",
        "site_type": "Maintenance Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-036",
        "site_name": "Cherry Point Aviation Sustainment Depot",
        "region": "Mid-Atlantic",
        "site_type": "Aviation Sustainment Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-037",
        "site_name": "Quantico Mission Support Center",
        "region": "Mid-Atlantic",
        "site_type": "Mission Support Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-038",
        "site_name": "Dahlgren Systems Readiness Site",
        "region": "Mid-Atlantic",
        "site_type": "Readiness Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-039",
        "site_name": "Aberdeen Proving Ground Supply Depot",
        "region": "Mid-Atlantic",
        "site_type": "Depot",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-040",
        "site_name": "Dover Strategic Airlift Parts Hub",
        "region": "Northeast",
        "site_type": "Parts Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-041",
        "site_name": "McGuire Joint Base Supply Center",
        "region": "Northeast",
        "site_type": "Supply Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-042",
        "site_name": "Tobyhanna Electronics Sustainment Depot",
        "region": "Northeast",
        "site_type": "Electronics Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-043",
        "site_name": "West Point Training Support Site",
        "region": "Northeast",
        "site_type": "Support Site",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-044",
        "site_name": "Hanscom Systems Logistics Center",
        "region": "Northeast",
        "site_type": "Logistics Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-045",
        "site_name": "New London Maritime Readiness Node",
        "region": "Northeast",
        "site_type": "Readiness Node",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-046",
        "site_name": "Wright-Patterson Air Systems Depot",
        "region": "Midwest",
        "site_type": "Air Systems Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-047",
        "site_name": "Rock Island Arsenal Supply Center",
        "region": "Midwest",
        "site_type": "Supply Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-048",
        "site_name": "Crane Naval Systems Sustainment Site",
        "region": "Midwest",
        "site_type": "Sustainment Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-049",
        "site_name": "Scott Joint Mobility Support Hub",
        "region": "Midwest",
        "site_type": "Mobility Support Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-050",
        "site_name": "Selfridge Air Readiness Center",
        "region": "Midwest",
        "site_type": "Readiness Center",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-051",
        "site_name": "Minneapolis Reserve Logistics Node",
        "region": "Midwest",
        "site_type": "Logistics Node",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-052",
        "site_name": "Whiteman Equipment Sustainment Hub",
        "region": "Midwest",
        "site_type": "Sustainment Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-053",
        "site_name": "Offutt Strategic Systems Supply Center",
        "region": "Midwest",
        "site_type": "Supply Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-054",
        "site_name": "Tinker Air Logistics Complex",
        "region": "South Central",
        "site_type": "Air Logistics Complex",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-055",
        "site_name": "Altus Mobility Training Supply Hub",
        "region": "South Central",
        "site_type": "Supply Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-056",
        "site_name": "Corpus Christi Aviation Repair Depot",
        "region": "South Central",
        "site_type": "Repair Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-057",
        "site_name": "San Antonio Medical Logistics Center",
        "region": "South Central",
        "site_type": "Medical Logistics Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-058",
        "site_name": "Kelly Field Sustainment Support Site",
        "region": "South Central",
        "site_type": "Support Site",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-059",
        "site_name": "Red River Ground Systems Depot",
        "region": "South Central",
        "site_type": "Ground Systems Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-060",
        "site_name": "Dyess Mobility Readiness Center",
        "region": "South Central",
        "site_type": "Readiness Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-061",
        "site_name": "Kirtland Space Support Logistics Hub",
        "region": "Mountain West",
        "site_type": "Logistics Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-062",
        "site_name": "Holloman Range Sustainment Node",
        "region": "Mountain West",
        "site_type": "Sustainment Node",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-063",
        "site_name": "Hill Air Logistics Complex",
        "region": "Mountain West",
        "site_type": "Air Logistics Complex",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-064",
        "site_name": "Tooele Munitions Support Depot",
        "region": "Mountain West",
        "site_type": "Support Depot",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-065",
        "site_name": "Cheyenne Mountain Systems Readiness Site",
        "region": "Mountain West",
        "site_type": "Readiness Site",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-066",
        "site_name": "Peterson Space Logistics Center",
        "region": "Mountain West",
        "site_type": "Logistics Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-067",
        "site_name": "Buckley Aerospace Supply Node",
        "region": "Mountain West",
        "site_type": "Supply Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-068",
        "site_name": "Nellis Test Range Support Depot",
        "region": "West",
        "site_type": "Support Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-069",
        "site_name": "Edwards Flight Test Logistics Center",
        "region": "West",
        "site_type": "Logistics Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-070",
        "site_name": "Vandenberg Space Launch Supply Hub",
        "region": "West",
        "site_type": "Supply Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-071",
        "site_name": "Travis Strategic Airlift Sustainment Center",
        "region": "West",
        "site_type": "Sustainment Center",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-072",
        "site_name": "Beale Reconnaissance Parts Depot",
        "region": "West",
        "site_type": "Parts Depot",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-073",
        "site_name": "Point Mugu Systems Maintenance Site",
        "region": "West",
        "site_type": "Maintenance Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-074",
        "site_name": "Port Hueneme Naval Supply Center",
        "region": "West",
        "site_type": "Supply Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-075",
        "site_name": "China Lake Test Support Hub",
        "region": "West",
        "site_type": "Support Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-076",
        "site_name": "Yuma Proving Ground Logistics Node",
        "region": "Southwest",
        "site_type": "Logistics Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-077",
        "site_name": "Luke Air Training Supply Center",
        "region": "Southwest",
        "site_type": "Supply Center",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-078",
        "site_name": "Davis-Monthan Aircraft Recovery Depot",
        "region": "Southwest",
        "site_type": "Recovery Depot",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-079",
        "site_name": "Miramar Aviation Readiness Hub",
        "region": "West",
        "site_type": "Readiness Hub",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-080",
        "site_name": "Twentynine Palms Ground Systems Support Site",
        "region": "West",
        "site_type": "Support Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-081",
        "site_name": "Bangor Strategic Systems Supply Depot",
        "region": "Pacific Northwest",
        "site_type": "Supply Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-082",
        "site_name": "Whidbey Island Aviation Sustainment Node",
        "region": "Pacific Northwest",
        "site_type": "Sustainment Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-083",
        "site_name": "Fairchild Mobility Support Center",
        "region": "Pacific Northwest",
        "site_type": "Support Center",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-084",
        "site_name": "Kings Bay Fleet Sustainment Depot",
        "region": "Southeast",
        "site_type": "Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-085",
        "site_name": "Huntsville Missile Systems Logistics Hub",
        "region": "Southeast",
        "site_type": "Logistics Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-086",
        "site_name": "Anniston Ground Vehicle Repair Depot",
        "region": "Southeast",
        "site_type": "Repair Depot",
        "mission_priority": 5,
        "active_flag": True,
    },
    {
        "site_id": "SITE-087",
        "site_name": "Blue Grass Equipment Sustainment Site",
        "region": "Southeast",
        "site_type": "Sustainment Site",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-088",
        "site_name": "Crane Lake Regional Storage Annex",
        "region": "Midwest",
        "site_type": "Storage Annex",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-089",
        "site_name": "Pine Ridge Forward Supply Annex",
        "region": "Mountain West",
        "site_type": "Supply Annex",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-090",
        "site_name": "Desert Mesa Maintenance Annex",
        "region": "Southwest",
        "site_type": "Maintenance Annex",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-091",
        "site_name": "Coastal Bend Logistics Annex",
        "region": "South Central",
        "site_type": "Logistics Annex",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-092",
        "site_name": "Great Lakes Reserve Supply Site",
        "region": "Midwest",
        "site_type": "Supply Site",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-093",
        "site_name": "Allegheny Component Storage Facility",
        "region": "Northeast",
        "site_type": "Storage Facility",
        "mission_priority": 2,
        "active_flag": True,
    },
    {
        "site_id": "SITE-094",
        "site_name": "Cape Fear Distribution Support Center",
        "region": "Southeast",
        "site_type": "Distribution Center",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-095",
        "site_name": "Gulf Coast Readiness Supply Hub",
        "region": "Southeast",
        "site_type": "Supply Hub",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-096",
        "site_name": "Ozark Field Maintenance Center",
        "region": "South Central",
        "site_type": "Maintenance Center",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-097",
        "site_name": "Sierra Nevada Logistics Support Site",
        "region": "West",
        "site_type": "Support Site",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-098",
        "site_name": "Cascade Regional Sustainment Hub",
        "region": "Pacific Northwest",
        "site_type": "Sustainment Hub",
        "mission_priority": 3,
        "active_flag": True,
    },
    {
        "site_id": "SITE-099",
        "site_name": "Arctic Circle Forward Supply Node",
        "region": "Alaska",
        "site_type": "Forward Supply Node",
        "mission_priority": 4,
        "active_flag": True,
    },
    {
        "site_id": "SITE-100",
        "site_name": "Pacific Rim Expeditionary Logistics Hub",
        "region": "Pacific",
        "site_type": "Expeditionary Logistics Hub",
        "mission_priority": 5,
        "active_flag": True,
    },
]