supplier_names = [
    "Apex Defense Components",
    "Summit Tactical Supply",
    "Ironclad Industrial Systems",
    "Patriot Precision Parts",
    "Vector Aerospace Supply",
    "Redstone Logistics Group",
    "Blue Ridge Defense Manufacturing",
    "Liberty Mechanical Systems",
    "Sentinel Equipment Supply",
    "Atlas Ground Support",
    "Frontier Aviation Components",
    "Keystone Industrial Supply",
    "Titan Mobility Systems",
    "Falcon Electronics Group",
    "Granite State Components",
    "Cedar Valley Manufacturing",
    "Pinnacle Hydraulic Systems",
    "Ranger Vehicle Parts",
    "Compass Maritime Supply",
    "Sterling Power Systems",
    "Evergreen Field Support",
    "Northstar Defense Supply",
    "Gulf Coast Maintenance Parts",
    "Prairie Technical Components",
    "Lone Star Equipment Group",
    "Cascade Aerospace Systems",
    "Heritage Logistics Supply",
    "Trident Marine Components",
    "Mesa Tactical Manufacturing",
    "Harborline Industrial Supply",
]